name: Release

on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '12'
    name: Release on node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: Run lint
        run: yarn lint
        env:
          CI: true
      - name: Run test
        run: yarn test:coverage
        env:
          CI: true
      - name: Build package
        run: yarn build
        env:
          CI: true
      - name: Publish to npm
        run: yarn publish-to-npm
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
